### PR TITLE
Control panel

### PR DESCRIPTION
**Pull request by hkbu-15200183**
Hope someone can build this gui first, if i build it must fail

### CODE REVIEW

**Comment by soumasandesu** [comment]
What is your proposed design of that `ControlPanel` with use of Swing?
For Eclipse, there must be some `WindowBuilder`, `JFormDesigner` extensions for Swing code generation
~~You may consider using JFormDesigner since my IDE IdeaJ is natively supporting its files.~~ No, it's shareware.

**Comment by hkgsherlock** [comment]
...I start putting JFormDesigner files then

**Comment by chlorella** [comment]
basically i am using WindowBuilder ^^

**Comment by soumasandesu** [comment]
rotfl me use Eclipse? eeenope

**Comment by chlorella** [comment]
ok if you want than switch to JFormDesigner :)
btw the building test seem no work with eclipse:)

**Comment by soumasandesu** [comment]
No, I'm just saying I'd rather let only one of us to design the interface. There's still a native feature in IdeaJ to design GUI Forms, but neither the design files of this nor that of Eclipse's WindowBuilder is convertible to another IDE. 
So, it's the decision of @hkbu-15200183 to choose who to work on it (but the logics).

**Comment by chlorella** [comment]
you can work on control panel than, i pay more hard on kiosk ^^

**Comment by hkbu-15200183** [comment]
I built GUI with only scrollable textarea on it, trying to build autoupdate info instead of pressing buttons to refresh it. I will upload another pull request then

**Pull request closed without merging**
